//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ANHFEEDBACK
    {
        [Display(Name = "Mã ảnh")]
        public int ID_ANH { get; set; }

        [Display(Name = "Mã feedback")]
        public Nullable<int> ID_FEEDBACK { get; set; }

        [Display(Name = "Ảnh")]
        public string ANH { get; set; }

        public virtual FEEDBACK FEEDBACK { get; set; }
    }
}
