//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANHFEEDBACK
    {
        public int ID_ANH { get; set; }
        public Nullable<int> ID_FEEDBACK { get; set; }
        public string ANH { get; set; }
    
        public virtual FEEDBACK FEEDBACK { get; set; }
    }
}
