//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BANGGIA
    {
        [Display(Name = "Mã")]
        public int ID_BANGGIA { get; set; }

        [Display(Name = "Mã sách")]
        public Nullable<int> ID_SACH { get; set; }

        [Display(Name = "Ngày áp dụng")]
        public string NGAY_APDUNG { get; set; }

        [Display(Name = "Tăng/ Giảm")]
        public bool TANG_GIAM { get; set; }

        [Display(Name = "Giá trị thay đổi")]
        public Nullable<double> GIATRI { get; set; }

        [Display(Name = "Sách")]
        public virtual SACH SACH { get; set; }
    }
}
