//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGGIA
    {
        public int ID_BANGGIA { get; set; }
        public Nullable<int> ID_SACH { get; set; }
        public string NGAY_APDUNG { get; set; }
        public Nullable<bool> TANG_GIAM { get; set; }
        public Nullable<double> GIATRI { get; set; }
    
        public virtual SACH SACH { get; set; }
        public List<SACH> lsSach { get; set; }
        public string minDate { get; set; }
    }
}
