//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int ID_CTDH { get; set; }
        public Nullable<int> ID_DONHANG { get; set; }
        public Nullable<int> ID_SACH { get; set; }
        public Nullable<int> ID_SPKM { get; set; }
        public Nullable<double> GIA_BAN { get; set; }
        public Nullable<short> SOLUONG { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SACH SACH { get; set; }
        public virtual SANPHAMKHUYENMAI SANPHAMKHUYENMAI { get; set; }
    }
}
