//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEUKIENKHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEUKIENKHUYENMAI()
        {
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public int ID_DIEUKIEN { get; set; }
        public string THOIGIAN_BATDAU { get; set; }
        public string THOIGIAN_KETTHUC { get; set; }
        public Nullable<double> MUC_TIEUDUNG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
    }
}
