//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.HOADONs = new HashSet<HOADON>();
        }
        [Display(Name = "Mã")]
        public int ID_DONHANG { get; set; }
        [Display(Name = "Mã thông tin khách hàng")]
        public Nullable<int> ID_TTKH { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<int> ID_TRANGTHAI { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<double> TONGTIEN { get; set; }
        [Display(Name = "Thời gian đặt")]
        public string THOIGIAN_DAT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual TRANGTHAIDONHANG TRANGTHAIDONHANG { get; set; }
        public virtual THONGTINKHACHHANG THONGTINKHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public List<DONHANG> lsDonHang { get; set; }
    }
}
