//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class TAIKHOANKHACHHANG
    {
        public int ID_KHACHHANG { get; set; }

        [Required(ErrorMessage = "Tên Đăng Nhập Không Được Trống")]
        [Display(Name = "Tên Đăng Nhập")]
        public string TEN_DANGNHAP { get; set; }

        [DisplayName("Mật Khẩu")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Mật Khẩu Không Được Trống")]
        public string MATKHAU { get; set; }

        public string ANH_DAIDIEN { get; set; }
        public Nullable<int> ID_LOAITK { get; set; }
        public Nullable<int> ID_TTKH { get; set; }

        [NotMapped]
        [DisplayName("Nhập Lại Mật Khẩu")]
        [Compare("MATKHAU")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        [NotMapped]
        public string ErrorLogin { get; set; }

        public virtual LOAITAIKHOAN LOAITAIKHOAN { get; set; }
        public virtual THONGTINKHACHHANG THONGTINKHACHHANG { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
