//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANNGANHANG
    {
        public int ID_TKNH { get; set; }
        public string TEN_NGANHANG { get; set; }
        public Nullable<int> MA_PIN { get; set; }
    }
}
