//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class TAIKHOANQUANTRIVIEN
    {
        public int ID_QUANTRIVIEN { get; set; }
        public string TEN_DANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string TEN_QUANTRIVIEN { get; set; }
        public string ANH_DAIDIEN { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
